### ISSUE TITLE
unknown message type 

### ISSUE THREAD

**Issue by jeffchanjunwei** [xunchangguo/restapi#1]
用了你的api，能帮忙看下，以下这个调用接口时的错误大概是什么原因么，另外你用的tiller是什么版本？

{
    "error": "unknown message type \".helmignore\"",
    "code": 2
}

**Comment by xunchangguo** [comment]
AppsCode Swift（https://github.com/appscode/swift） - Ajax friendly Helm Tiller Proxy using grpc-gateway（https://github.com/grpc-ecosystem/grpc-gateway）
用这个吧

**Comment by jeffchanjunwei** [comment]
@xunchangguo 谢啦，我再试下
